baseURL = "http://example.com/"
languageCode = "en-us"
title = "windedvertigo"
theme = "minimal"
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Garrett J Jaeger"
    description = "garrett jaeger collaborations"
    githubUsername = "jaegerjaeger"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "main"
    weight = 1

[[menu.main]]
    url = "/research/"
    name = "research"
    weight = 2

[[menu.main]]
    url = "/courses/"
    name = "courses"
    weight = 3

[[menu.main]]
    url = "/tools/"
    name = "tools"
    weight = 4

[[menu.main]]
    url = "/post/"
    name = "posts"
    weight = 5

[[menu.main]]
    url = "/cv/"
    name = "cv"
    weight = 6

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:garrett.jaeger@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/jaegerjaeger/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/jaeger/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/garrett-jaeger-bb51615/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/3230269/jaeger/"
    name = "stack-overflow"
    weight = 5
